version: 0.1

phases:
    install:
        commands:
            - yum install -y gcc libffi-devel python-devel openssl-devel
            - pip install -U pip virtualenv wheel
            - curl https://sh.rustup.rs -sSf | bash -s -- -y
            - export PATH=$PATH:$HOME/.cargo/bin
            - source $HOME/.cargo/env
            - echo $PATH
    build:
        commands:
            - source $HOME/.cargo/env
            - rustc --version
            #- bash build_cryptography_custom_openssl.sh
            #- mkdir site-packages
            #- pip install --target=site-packages --use-wheel --no-index --find-links=`pwd` cryptography

artifacts:
    files:
        - site-packages/**/*
        - lambda_entry.py
