version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - yum install -y gcc libffi-devel python-devel openssl-devel
            - pip install -U pip virtualenv wheel
    build:
        commands:
            #- bash build_cryptography_custom_openssl.sh
            
            # reference: https://community.snowflake.com/s/article/How-to-Use-Snowflake-with-AWS-Lambda
            - mkdir site-packages
            - virtualenv env
            - source env/bin/activate
            - pip install JayDeBeAPi==1.2.3 --target=site-packages
          
            
            #- pip install --target=site-packages --no-index --find-links=`pwd` cryptography
            #- pip install --target=site-packages pycryptodome
            
            #- pip install --target=site-packages -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v2.4.2/tested_requirements/requirements_38.reqs
            #- pip install --target=site-packages snowflake-connector-python==2.4.2
artifacts:
    files:
        - site-packages/**/*
        - lambda_entry.py
